# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: Default

steps:
- task: SonarCloudPrepare@3
  inputs:
    SonarQube: 'SONAR_CLOUD'
    organization: 'sonardec24'
    scannerMode: 'other'
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    sonarQubeRunAnalysis: false
    goals: 'package'
- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'
